#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

#include <driver/gpio.h>

#define BOARD_PUMP_1_GPIO GPIO_NUM_16
#define BOARD_PUMP_2_GPIO GPIO_NUM_17
#define BOARD_PUMP_3_GPIO GPIO_NUM_18
#define BOARD_PUMP_4_GPIO GPIO_NUM_19
#define BOARD_STIRRER_GPIO GPIO_NUM_21
#define BOARD_ICE_GPIO GPIO_NUM_22
#define BOARD_CLEAN_GPIO GPIO_NUM_23
#define BOARD_CUP_SENSOR_GPIO GPIO_NUM_34
#define BOARD_LID_SENSOR_GPIO GPIO_NUM_35

#define BOARD_SENSOR_ACTIVE_LEVEL 1
#define BOARD_ACTUATOR_ACTIVE_LEVEL 1
#define BOARD_PUMP_TIMEOUT_MS 15000
#define BOARD_STIR_TIMEOUT_MS 12000
#define BOARD_CLEAN_TIMEOUT_MS 10000

#endif
